config/routes.rb
Rails.application.routes.draw do
  get 'days/index'
  devise_for :users
  root to: "notes#index"
    resources :notes, only: [:new, :create,:edit,:update,:destroy,:show]
    resources :days
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  validates :start_time, presence: true
  belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
  has_many :days
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  protect_from_forgery with: :exception
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user
      @days = Day.all.where(user_id: current_user.id)
      @notes =Note.all.where(user_id: current_user.id)
      render "notes/index"
    else
      redirect_to new_user_session_path
    end
  end

  def new
    @day = Day.new
  end

  def create
    Day.create(day_params)
    redirect_to root_path
  end

  def edit
    @day = Day.find(params[:id])
  end

  def update
    day = Day.find(params[:id])
    day.update(day_params)
    redirect_to root_path
  end

  def show
    @day = Day.find(params[:id])
  end

  def destroy
    day= Day.find(params[:id])
    day.destroy
    redirect_to root_path
  end

  private
   def day_params
    params.require(:day).permit(:title, :content, :start_time).merge(user_id: current_user.id)
   end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    if current_user
      @notes = Note.includes(:user).where(user_id: current_user.id)
      @days =Day.all.where(user_id: current_user.id)
    else
      redirect_to new_user_session_path
    end
  end

  def new
    @note = Note.new
  end
  
  def create
    Note.create(note_params)
    redirect_to root_path
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    note = Note.find(params[:id])
    note.update(note_params)
    redirect_to root_path
  end

  def show
    @note = Note.find(params[:id])
  end

  def destroy
    note= Note.find(params[:id])
    note.destroy
    redirect_to root_path
  end


  private
    def note_params
      params.require(:note).permit(:text).merge(user_id: current_user.id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/days/_index.html.erb
<table>
  <thead>
    <tr>
      <th class="th-list" >予定一覧</th>
      <%# <th>時間<th> %>
      <%# <th colspan="3"></th> %>
    </tr>
  </thead>

  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= day.title %></td>
        <td><%= day.start_time.strftime("%Y-%m-%d %H:%M")%></td>
        <td><%= link_to "詳細", day%></td>
        <td><%= link_to "編集", edit_day_path(day.id)%></td>
        <td><%= link_to "削除",day_path(day.id),method: :delete, data: { confirm: '削除しますか' } %></td>
      </tr> 
    <% end %>
  </tbody>
</table>

<%= link_to "新規予定", new_day_path,class: "new-day" %>

<%= month_calendar events: @days do |date, days|%>
  <%= date.day %>

  <% days.each do |day| %>
    <div><%= link_to day.title, day %></div>
  <% end %>
<% end %>

app/views/days/edit.html.erb
<%= form_with(model: @day, local: true) do |form| %>

  <div class="title-label">
    <%= form.label :タイトル %>
  </div>
  <div class= "title-text">
    <%= form.text_field :title %>
  </div>

    <div class="time-label">
    <%= form.label :日付・時間 %>
    </div>
  <div class="time">
    <%= form.datetime_select  :start_time,{use_month_numbers: true}, {class: "time--box"} %>
  </div>

  <div class="content-label">
    <%= form.label :内容 %>
  </div>
  <div class="content-text">
    <%= form.text_area :content, class:"content-text--area" %>
  </div>


  <div class="submit">
    <%= form.submit :Update, class:"submit--btn"%>
  </div>

<% end %>

app/views/days/new.html.erb
<%= form_with(model: @day, local: true) do |f| %>
  <div class="title-label">
    <%= f.label :タイトル %>
  </div>
  <div class= "title-text">
    <%= f.text_field :title, class:"title-text--area" %>
  </div>

  <div class= "time-label">
    <%= f.label :日付・時間 %>
  </div>
  <div class= "time">
    <%= f.datetime_select :start_time,{use_month_numbers: true}, {class: "time--box"} %>
  </div>

  <div class= "content-label">
    <%= f.label :内容 %>
  </div>
  <div class= "content-text">
    <%= f.text_area :content, class:"content-text--area" %>
  </div>

  <div class= "submit">
    <%= f.submit :Save, class:"submit--btn" %>
  </div>

<% end %>

app/views/days/show.html.erb
<p>
  <strong>タイトル:<strong>
  <%= @day.title %>
</p>

<p>
  <strong>時間:<strong>
  <%= @day.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>内容:</strong>
  <%= safe_join(@day.content.split("\n"),tag(:br))%>
</p>

<div class= "show">
  <%= link_to "Edit", edit_day_path(@day),class: "show--edit" %>
  <%= link_to "Back", days_path,class: "show--back" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <div class= "header"> 
    <div class ="title" >
      <%= link_to "Mytask", root_path, class: "title__text"%>
    </div>
    <div class= right>
      <% if user_signed_in? %>
        <div class= "right__name">
          <%= current_user.nickname %>
        </div>
        <%= link_to "Log out",destroy_user_session_path, method: :delete, class: "right__btn" %>
      <% else %>
      <%= link_to "Login", new_user_session_path, class: "right__btn" %>
      <%= link_to "sign up", new_user_registration_path, class: "right__btn"%>
      <% end %>
    </div>
  </div>
<%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<%# <div class= "note-data">
  <%= @note.created_at %>
<%# </div> %>

<%# <div class= "note-text">
  <%=safe_join(@note.text.split("\n"),tag(:br))%>
<%# </div> %>

<div class="note-fix">  
  Edit and delete
</div>
<div class= "note-btn">
  <%= link_to "Delete",note_path(@note.id),method: :delete, class: "note-btn__delete" %>
</div>
<%= form_with model: @note, class: :form, local: true do |form| %>
  <%= form.text_area :text, placeholder: :作業内容, class: :form__text%>
  <%= form.submit "Update", class: :form__btn %>
<% end %>

app/views/notes/index.html.erb
<div class= "main">
  <div class="main-left">
    <%= render "days/index" %>
  </div>

  <div class= "main-right" >
    <% @notes.each do |note|%>
      <div class= "main-right__content">
        <%=link_to safe_join(note.text.split("\n"),tag(:br)),edit_note_path(note.id),class: "main-right__content--text" %>
      </div>
    <% end %>
    <div class= "main-right__new">
      <%= link_to "New work",new_note_path,class: "btn main-right__new--text"%>
    </div> 
  </div> 
</div>

app/views/notes/new.html.erb
<div class= "new_note">
  <div class ="new_title">
    New work
  </div>
</div>

<%= form_with model: @note, class: :form, local: true do |form| %>
  <%= form.text_area :text, placeholder: :作業内容, class: :form__text%>
  <%= form.submit "Save", class: :form__btn %>
<% end %>

app/views/notes/show.html.erb
<div class= "main">
  <div class="main-left">
    <%= month_calendar partial:"simple_calendar/calendar" do |data|%>
    <%= data.day %>
    <% end %>
    <%= render partial: ‘days/index’, locals: {days: @days} %>
  </div>
  
  <div class= "main-right">
    <% @note.each do |note|%>
      <div class= "main-right__content">
        <%=link_to safe_join(note.text.split("\n"),tag(:br)),edit_note_path(note.id),class: "main-right__content--text" %>
      </div>
    <% end %>
    <div class= "main-right__new">
      <%= link_to "New work",new_note_path,class: "main-right__new--text" %>
    </div>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '前月'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= start_date.year %>年&nbsp;<%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '来月'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>